### ISSUE TITLE
add hashKey and get

### ISSUE THREAD

**Issue by simonaberry** [openwar/mongodb-queue#998]
Q1: if you:

`queue.add(payload, { hashKey: '12' })`
`msg = queue.get();`
... //process
`queue.ack(msg.ack);`

... then a new add with the same id :
`queue.add(payload, { hashKey: '12' })`

I assume the second message  **is** added ? (and not ignored becasue it has the same *hashKey* as a completed/done message)

Q2: if you : 

`queue.add(payload, { hashKey: '12' })`
`msg = queue.get();`
... //process - long 

... then a new add with the same id  (added during the visibility window)
`queue.add(payload, { hashKey: '12' })`

// => will this be added as a new message or ignored as a duplicate

...//long process completes
`queue.ack(msg.ack);`

`msg = queue.get();` // ?? is this empty or does it have the second message ?

**Comment by alias-mac** [comment]
For Q1: If you have the same id then it won't be added because it will be considered a duplicated message that arrived for the second time after it was already processed. Keep in mind that `hashKey` is what field to use, not the value itself.
In your example above it doesn't make much sense because it assumes you have a `payload['12']` with some value and there is no guarantee that it is the same value on both.


Regarding Q2: it is similar to Q1 because the duplication depends on what is the value of `payload['12']`. It won't duplicate (regardless if it is processed or not).

This solution is to allow idempotency on events that were added multiple times in the queue but have a unique value that we can identify as being the same event.
